### ISSUE TITLE
Unavailable or private video in Music dataset

### ISSUE THREAD

**Issue by QichenZheng** [YapengTian/CCOL-CVPR21#2]
Hi, The Music dataset provided in the json contains only the IDs of Youtube videos. I downloaded them but found that many videos  is not available now, such as "flute azUffG1Ao8U". Could you please share the dataset you have downloaded before on the network disk for us to download.
Thank you!

**Comment by YapengTian** [comment]
Due to the license issue, I cannot directly make the downloaded videos publicly available. But, if you can send me an Email, I can send the missing videos to you individually.

**Comment by yy199891** [comment]
> Due to the license issue, I cannot directly make the downloaded videos publicly available. But, if you can send me an Email, I can send the missing videos to you individually.

Hello, can you send me one too?1140523469@qq.com.Thank you!

**Comment by YapengTian** [comment]
The whole set is too huge. Could you send me a missing data list?

**Comment by yy199891** [comment]
> The whole set is too huge. Could you send me a missing data list?

[missing videos.txt](https://github.com/YapengTian/CCOL-CVPR21/files/7299994/missing.videos.txt)

**Comment by YapengTian** [comment]
The frames and detection results used in the paper can be downloaded from this [link](https://drive.google.com/drive/folders/15dKDqXAfLlv55iGwipRCSnJXjumy4tLi?usp=sharing).
