### ISSUE TITLE
ask for the data preprocess

### ISSUE THREAD

**Issue by runzeer** [YapengTian/CCOL-CVPR21#3]
Hi,
     I have some issues for the data preprocess especially for the audio file generation. So if convenient, could you tell me how you can Extract  waveforms at 11025Hz from videos. Could you tell me the tools or pip package that you used?

**Comment by YapengTian** [comment]
Please check this script: https://github.com/YapengTian/CCOL-CVPR21/blob/master/code/scripts/extract_audio.py.

**Comment by runzeer** [comment]
Thanks a lot!!
